### ISSUE TITLE
Uncaught undefined in tweet splitter

### ISSUE THREAD

**Issue by QuinnyPig** [louisgrasset/touitomamout#174]
This was working fine until a few days ago, then it started throwing this trace; any tips on how to figure out what it's choking on / get it to handle the failure gracefully?

│ content-mapper  ✔ tweets: total: 14 retweets: 0 replies: 0 quotes: 0                                                                                                                                  │
│ content-mapper  ✔ task finished                                                                                                                                                                       │
│ TypeError: Cannot read properties of undefined (reading 'matchAll')                                                                                                                                   │
│     at file:///app/dist/helpers/tweet/split-tweet-text/extract-words-and-spacers.js:36:34                                                                                                             │
│     at Array.forEach (<anonymous>)                                                                                                                                                                    │
│     at extractWordsAndSpacers (file:///app/dist/helpers/tweet/split-tweet-text/extract-words-and-spacers.js:35:13)                                                                                    │
│     at splitTweetText (file:///app/dist/helpers/tweet/split-tweet-text/split-tweet-text.js:23:21)                                                                                                     │
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                                     │
│     at async makeBlueskyPost (file:///app/dist/helpers/post/make-bluesky-post.js:40:17)                                                                                                               │
│     at async makePost (file:///app/dist/helpers/post/make-post.js:29:23)                                                                                                                              │
│     at async postsSynchronizerService (file:///app/dist/services/posts-synchronizer.service.js:26:70)                                                                                                 │
│     at async touitomamout (file:///app/dist/index.js:21:31)                                                                                                                                           │
│     at async file:///app/dist/index.js:33:1                                                                                                                                                           │
│

**Comment by QuinnyPig** [comment]
I've deleted the tweet, but the newentries object [here](https://github.com/louisgrasset/touitomamout/blob/main/src/helpers/tweet/split-tweet-text/extract-words-and-spacers.ts#L46) was:

```[
  {
    str: 'Volkswagen got caught cheating on emissions tests.\n' +
      '\n' +
      'Obviously, someone then created Volkswagen (a CI/CD tool that always passes if in a CI environment). ',
    sep: ''
  },
  { str: 'https://github.com/auchenberg/volkswagen', sep: ' ' },
  {
    str: '\n' +
      '\n' +
      'Then Volkswagen ACTUALLY DID A CI/CD JOINT VENTURE https://www.volkswagen-newsroom.com/en/press-releases/volkswagen-and-tracetronic-establish-neocx-a-joint-venture-for-automated-software-integration-7378',
    sep: ''
  },
  { str: '', sep: '' },
  {
    str: 'https://www.volkswagen-newsroom.com/en/press-releases/volkswagen-and-tracetronic-establish-neocx-a-joint-venture-for-automated-software-integration-7378',
    sep: ''
  },
  { str: undefined, sep: '' }
]```
The `undefined` caused it to choke. 

The
