### ISSUE TITLE
Twitter Login not working anymore

### ISSUE THREAD

**Issue by trfetzer** [louisgrasset/touitomamout#193]
**Twitter login**
I have been unable to get this awesome tool to run with twitter login after having turned off MFA. Without the authentication it only posted a single post from several months ago, but nothing else.

The error I am getting when providing the credentials

2024-08-17 16:34:23 (node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
2024-08-17 16:34:23 (Use `node --trace-warnings ...` to show where the warning was created)
2024-08-17 16:34:23 ⚙️ cache        ✔ task finished
2024-08-17 16:34:23 - connecting to twitter...
2024-08-17 16:34:24 Error: Unknown subtask ArkoseLogin
2024-08-17 16:34:24     at TwitterUserAuth.login (/app/node_modules/@the-convocation/twitter-scraper/dist/auth-user.js:85:23)
2024-08-17 16:34:24     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-17 16:34:24     at async Scraper.login (/app/node_modules/@the-convocation/twitter-scraper/dist/scraper.js:264:9)
2024-08-17 16:34:24     at async handleTwitterAuth (file:///app/dist/helpers/auth/handle-twitter-auth.js:22:9)
2024-08-17 16:34:24     at async configuration (file:///app/dist/configuration/configuration.js:53:5)
2024-08-17 16:34:24     at async file:///app/dist/index.js:4:121
2024-08-17 16:34:26 (node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
2024-08-17 16:34:26 (Use `node --trace-warnings ...` to show where the warning was created)

**Comment by louisgrasset** [comment]
Oh I don't like this. 

`Arkos` logins are basically captchas. And I don't have any quick fix for that 🥸

**Comment by trfetzer** [comment]
Thanks, I think I found a workaround, its much better this way actually.
