### ISSUE TITLE
New Tweets Not Synching

### ISSUE THREAD

**Issue by hawkblogger** [louisgrasset/touitomamout#231]
**Describe the bug**
Twitter -> Bluesky syncing runs in Docker without error.
It synched 2 posts on first run. Those 2 posts were 17 days old.
No newer posts were synched.
I created a new Twitter post and the job ran, and it still is not syncing any new posts. 

**To Reproduce**
See above. Nothing else of note.
I am using the cookie json in my env to authenticate with Twitter, if that matters.

**Expected behavior**
New tweets would sync

**Screenshots**

**Additional supporting information**

**Comment by hawkblogger** [comment]
I have now been able to get the credentials to work, and it is seeing the tweets, but not syncing anything more recent than 13 days ago. Does it not know how to handle a Bsky account that has "original" bsky posts? In other words, does this only work on bsky accounts that have never posted unique content?

**Comment by hawkblogger** [comment]
I tried a fresh bsky account to make sure there was not a problem with conflict resolution and still seeing the same issue. Nothing newer than 13 days ago. I am seeing this error:

TypeError: Cannot read properties of undefined (reading 'matchAll')
    at file:///app/dist/index.js:11546:21
    at Array.forEach (<anonymous>)
    at gl (file:///app/dist/index.js:11545:12)
    at Ki (file:///app/dist/index.js:11581:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Il (file:///app/dist/index.js:11619:13)
    at async Ol (file:///app/dist/index.js:11652:13)
    at async Gl (file:///app/dist/index.js:11747:40)
    at async vi (file:///app/dist/index.js:11976:13)
    at async file:///app/dist/index.js:11989:1

Wondering if the issue is on the bsky posting side

**Comment by hawkblogger** [comment]
Hi Louis,

Thanks for the reply. I have managed to get it working via manual sync
instead of using Docker. I will try Docker again soon. This is such a
valuable contribution. Thank you for your work. I will make a
contribution in a bit. If you add Threads syncing, that would be amazing!
:)
