### ISSUE TITLE
Error code 366: missing data

### ISSUE THREAD

**Issue by eudemocracystiftung** [louisgrasset/touitomamout#242]
Since my previous attempt to sync an account that wasn't mine did not work (see #241), I am trying with a twitter account that is actually mine but hitting another error.

```
2024-12-02 17:03:38 touitomamout  | ⚙️ cache        ✔ task finished
2024-12-02 17:03:38 touitomamout  | - connecting to twitter...
2024-12-02 17:03:38 touitomamout  | 
2024-12-02 17:03:38 touitomamout  | [touitomamout] Error: Unable to restore cookies
2024-12-02 17:03:38 touitomamout  |                └─ Logging in with credentials instead.
2024-12-02 17:03:38 touitomamout  |                └─ 🦣.
2024-12-02 17:03:40 touitomamout  | Error: {"errors":[{"code":366,"message":"Missing data."}]}
2024-12-02 17:03:40 touitomamout  |     at TwitterUserAuth.executeFlowTask (file:///app/node_modules/@the-convocation/twitter-scraper/dist/node/esm/index.mjs:553:38)
2024-12-02 17:03:40 touitomamout  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-02 17:03:40 touitomamout  |     at async TwitterUserAuth.handleEnterAlternateIdentifierSubtask (file:///app/node_modules/@the-convocation/twitter-scraper/dist/node/esm/index.mjs:423:12)
2024-12-02 17:03:40 touitomamout  |     at async TwitterUserAuth.login (file:///app/node_modules/@the-convocation/twitter-scraper/dist/node/esm/index.mjs:331:16)
2024-12-02 17:03:40 touitomamout  |     at async Scraper.login (file:///app/node_modules/@the-convocation/twitter-scraper/dist/node/esm/index.mjs:2022:5)
2024-12-02 17:03:40 touitomamout  |     at async Rl (file:///app/dist/index.js:10998:84)
2024-12-02 17:03:40 touitomamout  |     at async hl (file:///app/dist/index.js:11164:3)
2024-12-02 17:03:40 touitomamout  |     at async file:///app/dist/index.js:11964:5
```

Any ideas?

**Comment by netarcx** [comment]
I solved this error by using a chrome plugin to download the twitter cookies manually and pasting them into the cookies.{username}.json file.
