### ISSUE TITLE
XRPCError: XRPC Not Supported

### ISSUE THREAD

**Issue by thomasbnt** [louisgrasset/touitomamout#80]
**Describe the bug**
I would like to run the script on my **Raspberry Pi 4**, but got the "XRPCError: XRPC Not Supported" error.

**To Reproduce**
1. Clone the repo
2. Installing packages
3. Fill `.env`
4. Execute `node dist/index.js .env`
5. got the error

**Expected behavior**

```shell
hey@raspfour:~/touitomamout $ node dist/index.js .env
🦤 client: ✔ connected as guest | replies will not be synced
🦣 client: ✔ connected
(node:18910) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
XRPCError: XRPC Not Supported
    at ServiceClient.call (/home/hey/touitomamout/node_modules/@atproto/api/dist/index.js:15584:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BskyAgent.login (/home/hey/touitomamout/node_modules/@atproto/api/dist/index.js:26483:19)
    at async configuration (file:///home/hey/touitomamout/dist/configuration/configuration.js:49:9)
    at async file:///home/hey/touitomamout/dist/index.js:4:120 {
  status: 404,
  error: 'XRPCNotSupported',
  success: false,
  headers: undefined
}
``` 

**Additional supporting information**

Version "Raspbian GNU/Linux 11 (bullseye)"

**Comment by louisgrasset** [comment]
The XRPCError is coming from the AT Protocol (underlying system to communicated with Bluesky).
Can you share the values you wrote for BLUESKY_INSTANCE & BLUESKY_IDENTIFIER?
